// mytask.h

#ifndef MYTASK_H
#define MYTASK_H

#include <QRunnable>
#include <QObject>
#include <QRunnable>
#include <QString>
#include "reseau/protocoleodc_serveur.h"
#include "moteur/MoteurCalculs.h"
#include "moteur/List.h"
#include <QDebug>

// Q_OBJECT missing in the original file generated by class wizard.
// because we set this class with base class QRunnable
// with no inheritance in the class wizard
// We do not have this. So, we cannot use signal/slot
// But we need them.
// Thus, we should use multiple inheritance: QObject inserted here

class MyTask : public QObject, public QRunnable
{
    Q_OBJECT
public:
    MyTask(QString messageClient);
private:
    QString m_messageClient;
signals:
    // notify to the main thread when we're done
    void Result(QString message);

protected:
    void run();
};

#endif // MYTASK_H
